title:             Madb33
email:             low_buffer@naver.com
description:       pwnable, revering, Deep Learning, etc...
author:            Madb33
baseurl:           "/"
url:               "https://buffer625.github.io"

# Social Profiles
twitter_username:  Mad_b33
github_username:   Madb33
facebook_username: Buffer625

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
